QuestionService transition
HSFDWS23-24/ShortcutTrainer-backEnd pull request #34
Opened 2023-12-19 17:48 UTC by Hamid-Keshavarz

2023-12-20 10:10 UTC, BravoEchoNov requested changes

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Controllers/QuestionController.cs
> +        public async Task<IActionResult> GetUnansweredQuestions(int courseId, string language, string system, string userId)
userId als erster Parameter und nullable

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Controllers/QuestionController.cs
> +        public async Task<IActionResult> GetIncorrectQuestions(int courseId, string language, string system, string userId)
userId als erster Parameter und nullable

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Controllers/QuestionController.cs
> +                var unansweredQuestions = await _questionService.GetUnansweredQuestionsAsync(courseId, language, system, userId);
userId als erster Parameter und nullable

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Controllers/QuestionController.cs
> +                var incorrectQuestions = await _questionService.GetIncorrectQuestionsAsync(courseId, language, system, userId);
userId als erster Parameter und nullable

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Controllers/QuestionController.cs
> +        public async Task<IActionResult> GetCorrectQuestions(int courseId, string language, string system, string userId)
userId als erster Parameter und nullable

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Controllers/QuestionController.cs
> +                var correctQuestions = await _questionService.GetCorrectQuestionsAsync(courseId, language, system, userId);
userId als erster Parameter und nullable

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Controllers/QuestionController.cs
> +        public async Task<IActionResult> UpdateQuestionStatus(int questionId, string userId, string questionStatus)
userId als erster Parameter und nullable

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Controllers/QuestionController.cs
> +                await _questionService.UpdateQuestionStatusAsync(questionId, userId, questionStatus);
userId als erster Parameter und nullable

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Services/Interfaces/IQuestionService.cs
> +        // GetUnansweredQuestions
userId immer als erstes und nullable. Alle Methoden fragen Fragen und Antworten in irgendeiner Form ab. Du kannst dir überlegen, welchen Teil der LINQ-Query alle gemeinsam haben und diese Abfrage in eine eigene private Methode packen. Damit erhöhst du die Lesbarkeit und reduzierst die LOC

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Data/Models/Answer.cs
> +using ShortcutTrainerBackend.Data.TransferObjects;
Ist obsolet. Außerdem kann QuestionParameter gelöscht werden

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Services/QuestionService.cs
>          public async Task<IEnumerable<DtoQuestion>> GetQuestionsAsync(int courseId, string language, string system)
GetQuestions könnte auch erweitert werden und alle Fragen und Antworten samt Status liefern. Dafür auch wieder userId als erster Parameter und wieder nullable

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Services/QuestionService.cs
> +                .Where(q => q.Course.Id == courseId && q.Course.Language == language)
Bei gegebenem User, also userId != null, kannst du auch über UserCourse abfragen

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Services/QuestionService.cs
> +            q.Answers.Any() &&
Die Einrückung beachten -> mit jedem Sub-Command ein Tab weiter rein

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Services/QuestionService.cs
> +                                await Task.Run(() => unitOfWork.CommitChanges());
Du benötigst kein UnitOfWork.CommitChanges -> das du nur ein Objekt speichern möchtest, kannst du auch
await _session.SaveChangesAsync(<Dein zu speicherndes Objekt>); verwenden

2023-12-20 10:10 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Services/QuestionService.cs
> +            {
Das Statement ist insgesamt zu komplex. Du brauchst kein 3-fach-verschachteltes If-Statement. Außerdem existieren die Funktionen, die du verwendest auch schon für die Klasse Session. Ohne das Statement noch tiefergehender zu überprüfen, überlege dir am besten was du brauchst und wie du es am geschicktesten Aufbauen kannst

2024-01-16 09:48 UTC, BravoEchoNov requested changes

2024-01-16 09:48 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Controllers/CourseController.cs
> +            return Ok(await _coursesService.GetCoursesAsync(language, system, searchString, limit));
warum hast du eine Änderung, die die Course-Route betreffen?
Im CourseService und im CourseController sind Fehler. Daher warten bis die Kurs-Überarbeitung gemerged ist und dann einfach aktualisieren

2024-01-16 09:48 UTC, BravoEchoNov commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Services/QuestionService.cs
> +        {
es fehlt noch ein Mechanismus, der unbeantwortete Fragen in der DB ergänzt, da es bisher noch nichts gibt. Es wäre unter Umständen gar nicht notwendig einen separaten Status "Unanswered" zu haben. D.h. du könntest auch einfach alle Fragen zurückgeben, für die es für die angegebenen Parameter noch keine Einträge gibt (also abhängig von Language und System)

2024-01-16 14:19 UTC, Hamid-Keshavarz commented on ShortcutTrainerBackend/ShortcutTrainerBackend/Controllers/CourseController.cs
> +            return Ok(await _coursesService.GetCoursesAsync(language, system, searchString, limit));
Ich habe etwas ausprobiert und einfach vergessen, die Änderung rückgängig zu machen.

2024-01-22 20:15 UTC, BravoEchoNov approved these changes

2024-01-22 20:15 UTC, merged